<a href="https://colab.research.google.com/github/StalkYy-06/5CS037-2024/blob/main/week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem - 1: Array Creation:

In [ ]:
import numpy as np;
# Initialize an empty array with size 2X2.
empty_arr = np.empty(shape=(2,2));
print(empty_arr);

# Initialize an all one array with size 4X2.
one_arr = np.ones(shape=(4,2));
print(one_arr);



[[4.68872040e-310 0.00000000e+000]
 [6.84066738e-310 6.84066735e-310]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Return a new array of given shape and type, filled with fill value.
# qsn 1
filled_arr=np.full((2,2),10);
print(filled_arr);

#qsn 2
filled2_arr=np.full((4,2),10);
print(filled2_arr);

[[10 10]
 [10 10]]
[[10 10]
 [10 10]
 [10 10]
 [10 10]]


In [ ]:
#Return a new array of zeros with same shape and type as a given array.

#qsn 1
zeros_arr=np.zeros_like(filled_arr);
print(zeros_arr);

#qsn 2
zeros_arr2=np.zeros_like(filled2_arr);
print(zeros_arr2);

[[0 0]
 [0 0]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# Return a new array of ones with same shape and type as a given array.
#qsn 1
ones_arr=np.ones_like(filled_arr);
print(ones_arr);

#qsn 2
ones_arr2=np.ones_like(filled2_arr);
print(ones_arr2);

[[1 1]
 [1 1]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
# For an existing list new_list = [1,2,3,4] convert to an numpy array.
new_list=[1,2,3,4];
array=np.array(new_list);
print(array);

[1 2 3 4]


# Problem - 2: Array Manipulation:

In [ ]:
# Create an array with values ranging from 10 to 49.
arr1=np.arange(10,50);
print(arr1);

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Create a 3X3 matrix with values ranging from 0 to 8.
arr2=np.arange(0,9).reshape((3,3));
print(arr2);


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Create a 3X3 identity matrix.
arr3=np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Create a random array of size 30 and find the mean of the array.
arr4=np.random.random(30);
print(arr4);
print("mean = ",np.mean(arr4));

[0.82612044 0.02293057 0.09223118 0.09767376 0.63242605 0.84549868
 0.76526202 0.82446887 0.78384694 0.51986417 0.0130081  0.14058655
 0.38602828 0.79497018 0.18341914 0.74053163 0.28110175 0.03490918
 0.47227179 0.19967623 0.85169032 0.34955137 0.54196324 0.26887387
 0.43825373 0.45854149 0.87905515 0.23199281 0.57120437 0.12748257]
mean =  0.44584781487513064


In [ ]:
# Create a 10X10 array with random values and find the minimum and maximum values.
arr5=np.random.random((10,10));
print(arr5);
print("min = ",np.min(arr5));
print("max = ",np.max(arr5));

[[0.84248606 0.61309036 0.42538989 0.01130804 0.39917664 0.28395404
  0.05180746 0.16627826 0.56766753 0.15195192]
 [0.48510005 0.69497149 0.13450682 0.35749413 0.24936972 0.75464329
  0.81202572 0.61831465 0.27307863 0.51604975]
 [0.72674091 0.60436269 0.56969319 0.9391207  0.46971499 0.74117308
  0.44635801 0.12024879 0.56822091 0.76754821]
 [0.96059337 0.56144953 0.14798084 0.3571125  0.36079222 0.07181217
  0.30483459 0.09660626 0.18066296 0.39753961]
 [0.89059416 0.83829419 0.1743837  0.44070555 0.13331814 0.94192458
  0.92564953 0.82477903 0.53691865 0.77059301]
 [0.80108076 0.46841202 0.19710193 0.11131002 0.26528925 0.08528767
  0.89797482 0.62773816 0.93944144 0.59602051]
 [0.57654158 0.42860298 0.64822211 0.38673006 0.72085417 0.43567457
  0.3545002  0.50594855 0.92439343 0.91630614]
 [0.71804059 0.57745055 0.40901184 0.89914574 0.23142295 0.48816744
  0.23518154 0.36888554 0.56983183 0.74876762]
 [0.9133111  0.2028068  0.48382649 0.39371018 0.55529343 0.142733
  0.82449675 0

In [3]:
# Create a zero array of size 10 and replace 5th element with 1.
import numpy as np

arr6= np.zeros(10);
arr6[4]=1;
print(arr6);

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
# Reverse an array arr = [1,2,0,0,4,0].
arr7 =[1,2,0,0,4,0]
revarr =np.flip(arr7)
revarr

array([0, 4, 0, 0, 2, 1])

In [5]:
# Create a 2d array with 1 on border and 0 inside.
orig_array = np.ones([3,3])
print(f"Original Array :\n{orig_array}")
orig_array[1][1]=0
print(f"Modified Array :\n{orig_array}")

Original Array :
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Modified Array :
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [6]:
# Create a 8X8 matrix and fill it with a checkerboard pattern.
checkboard = np.zeros([8,8])
print(f"Original Array: \n{checkboard}")
checkboard[1::2,::2] = 1
checkboard[::2,1::2] = 1
print(f"Modified Array: \n{checkboard}")

Original Array: 
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Modified Array: 
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# Problem -3: Array Operations:

In [8]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [10]:
# Add the two array.
print(f"First output: \n{np.add(x,y)}\n")
print(f"Second output: \n{np.add(v,w)}")

First output: 
[[ 6  8]
 [10 13]]

Second output: 
[20 22]


In [11]:
# Subtract the two array
print(f"First output: \n{np.subtract(x,y)}\n")
print(f"Second output: \n{np.subtract(v,w)}")

First output: 
[[-4 -4]
 [-4 -3]]

Second output: 
[-2 -2]


In [12]:
# Multiply the array with any integers of your choice.
print(f"First : \n{x*5}\n")
print(f"Second : \n{y*5}\n")
print(f"Third : \n{v*5}\n")
print(f"Fourth : \n{w*5}")

First : 
[[ 5 10]
 [15 25]]

Second : 
[[25 30]
 [35 40]]

Third : 
[45 50]

Fourth : 
[55 60]


In [13]:
# Find the square of each element of the array.
print(f"{x*x}\n")
print(f"{y*y}\n")
print(f"{v*v}\n")
print(f"{w*w}")

[[ 1  4]
 [ 9 25]]

[[25 36]
 [49 64]]

[ 81 100]

[121 144]


In [14]:
# Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print(f"First : \n{np.dot(v,w)}\n")
print(f"Second : \n{np.dot(x,v)}\n")
print(f"Third : \n{np.dot(x,y)}")

First : 
219

Second : 
[29 77]

Third : 
[[19 22]
 [50 58]]


In [16]:
# Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.
print(f"First : \n{np.concatenate((x,y),axis=0)}\n")
print(f"Second : \n{np.concatenate((v,w),axis=0)}\n")

First : 
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Second : 
[ 9 10 11 12]



In [17]:
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
print(f"Output: {np.concatenate((x,v),axis=1)}")

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

We get and error while concatenating x and v because they are of different dimensions.

# Problem -4: Matrix Operations:

In [18]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
print(f"A:\n{A} \nB:\n{B}")

A:
[[3 4]
 [7 8]] 
B:
[[5 3]
 [2 1]]


In [19]:
# Prove A.A-1 =I.
Ainv = np.linalg.inv(A)
print(f"Ainv:\n{Ainv}")
print(f"A.Ainv:\n{np.dot(A,Ainv)}")

Ainv:
[[-2.    1.  ]
 [ 1.75 -0.75]]
A.Ainv:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [20]:
# Prove AB /= BA.
print(f"AB:\n{np.dot(A,B)}")
print(f"BA:\n{np.dot(B,A)}")

AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]


In [21]:
# Prove (AB)T = BT.AT.
AB=np.dot(A,B)
BT=np.transpose(B)
AT=np.transpose(A)
print(f"AB.T:\n{np.transpose(AB)}")
print(f"BT.AT:\n{np.dot(BT,AT)}")


AB.T:
[[23 51]
 [13 29]]
BT.AT:
[[23 51]
 [13 29]]


In [22]:
# Solve the following system of Linear equation using Inverse Methods.
#2x − 3y + z = −1
#x − y + 2z = −3
#3x + y − z = 9

A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([-1,-3,9])
X=np.linalg.inv(A).dot(B)
print(f"x={X[0]}\ny{X[1]}\nz={X[2]}")

x=2.0
y1.0
z=-2.0


# Experiment: How Fast Is Numpy?

## 1. Element wise Addition

In [23]:
import random
from timeit import timeit
def add_python(Z1,Z2):
  return [z1+z2 for z1,z2 in zip(Z1,Z2)]
def add_numpy(Z1,Z2):
  return np.add(Z1,Z2)
size=1000000
Z1_list=random.sample(range(size+1),size)
Z2_list=random.sample(range(size+1),size)
Z1_np=np.array(Z1_list)
Z2_np=np.array(Z2_list)
python_time=timeit("add_python(Z1_list,Z2_list)",number=1,globals=globals())
numpy_time=timeit("add_numpy(Z1_np,Z2_np)",number=1,globals=globals())
print("Python Time:",python_time)
print("Numpy Time:",numpy_time)

Python Time: 0.35446861199989144
Numpy Time: 0.002062510000087059


## 2.Element wise Multiplication

In [24]:
def mul_python(Z1,Z2):
  return [z1*z2 for z1,z2 in zip(Z1,Z2)]
def mul_numpy(Z1,Z2):
  return np.multiply(Z1,Z2)
size=1000000
Z1_list=random.sample(range(size+1),size)
Z2_list=random.sample(range(size+1),size)
Z1_np=np.array(Z1_list)
Z2_np=np.array(Z2_list)
python_time=timeit("mul_python(Z1_list,Z2_list)",number=1,globals=globals())
numpy_time=timeit("mul_numpy(Z1_np,Z2_np)",number=1,globals=globals())
print("Python Time:",python_time)
print("Numpy Time:",numpy_time)

Python Time: 0.37102414800006045
Numpy Time: 0.0021490750000339176


## 3.Dot product

In [25]:
def dot_python(Z1,Z2):
  return sum(z1*z2 for z1,z2 in zip(Z1,Z2))
def dot_numpy(Z1,Z2):
  return np.dot(Z1,Z2)
size=1000000
Z1_list=random.sample(range(size+1),size)
Z2_list=random.sample(range(size+1),size)
Z1_np=np.array(Z1_list)
Z2_np=np.array(Z2_list)
python_time=timeit("dot_python(Z1_list,Z2_list)",number=1,globals=globals())
numpy_time=timeit("dot_numpy(Z1_np,Z2_np)",number=1,globals=globals())
print("Python Time:",python_time)
print("Numpy Time:",numpy_time)

Python Time: 0.45553182999992714
Numpy Time: 0.0017888630000015837


## 4. Matrix Multiplication

In [ ]:
size=1000
Z1_list = [random.sample(range(size),size) for _ in range(size)]
Z2_list = [random.sample(range(size),size) for _ in range(size)]
Z1_np = np.array(Z1_list)
Z2_np = np.array(Z2_list)
def np_matmul(Z1,Z2):
  return np.matmul(Z1,Z2)
def python_matmul(Z1,Z2):
  return [[sum(z1*z2 for z1,z2 in zip(Z1_row,Z2_col)) for Z2_col in zip(*Z2)] for Z1_row in Z1]
python_time=timeit("python_matmul(Z1_list,Z2_list)",number=1,globals=globals())
numpy_time=timeit("np_matmul(Z1_np,Z2_np)",number=1,globals=globals())
print("Python Time:",python_time)
print("Numpy Time:",numpy_time)